[2025-07-22 15:01:25,119 - cnnClassifierLogger - INFO - Logging is set up successfully.]
[2025-07-23 17:49:17,033: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 17:49:17,044: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 17:49:17,046: INFO: common: created directory at: artifacts]
[2025-07-23 17:49:17,051: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 17:49:17,054: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 17:49:29,413: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 17:57:18,652: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 17:57:18,657: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 17:57:18,659: INFO: common: created directory at: artifacts]
[2025-07-23 17:57:18,662: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 17:57:18,664: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 17:57:29,499: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 18:04:25,400: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-23 18:04:25,403: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 18:04:25,406: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 18:04:25,407: INFO: common: created directory at: artifacts]
[2025-07-23 18:04:25,408: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 18:04:25,408: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 18:04:36,313: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 18:04:36,875: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-23 18:33:53,641: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 18:33:53,646: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 18:33:53,648: INFO: common: created directory at: artifacts]
[2025-07-23 18:33:53,650: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-23 18:34:06,246: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-23 18:54:01,453: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-23 18:54:01,459: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 18:54:01,467: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 18:54:01,469: INFO: common: created directory at: artifacts]
[2025-07-23 18:54:01,470: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 18:54:01,471: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 11, in <module>
    obj.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_injestion.py", line 13, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 25, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL'
[2025-07-23 18:58:05,851: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-23 18:58:05,854: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 18:58:05,856: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 18:58:05,857: INFO: common: created directory at: artifacts]
[2025-07-23 18:58:05,858: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 18:58:05,858: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 11, in <module>
    obj.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_injestion.py", line 13, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 25, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL'
[2025-07-23 18:58:47,876: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 18:58:47,880: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 18:58:47,882: INFO: common: created directory at: artifacts]
[2025-07-23 18:58:47,884: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 18:58:47,886: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 18:58:59,176: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 19:05:16,870: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-23 19:05:16,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 19:05:16,876: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 19:05:16,876: INFO: common: created directory at: artifacts]
[2025-07-23 19:05:16,877: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 19:05:16,877: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 11, in <module>
    obj.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_injestion.py", line 13, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 25, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL'
[2025-07-23 19:05:26,715: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 19:05:26,720: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 19:05:26,722: INFO: common: created directory at: artifacts]
[2025-07-23 19:05:26,724: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 19:05:26,725: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 19:05:37,723: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 19:06:04,108: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 19:06:04,113: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 19:06:04,116: INFO: common: created directory at: artifacts]
[2025-07-23 19:06:04,119: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-23 19:06:04,665: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-23 19:06:25,934: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-23 19:06:25,939: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 19:06:25,941: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 19:06:25,943: INFO: common: created directory at: artifacts]
[2025-07-23 19:06:25,943: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 19:06:25,944: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 11, in <module>
    obj.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_injestion.py", line 13, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 25, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL'
[2025-07-23 19:08:54,240: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-23 19:08:54,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 19:08:54,245: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 19:08:54,246: INFO: common: created directory at: artifacts]
[2025-07-23 19:08:54,246: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 19:08:54,246: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 11, in <module>
    obj.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_injestion.py", line 13, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 27, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL'
[2025-07-23 19:09:26,041: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-23 19:09:26,044: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 19:09:26,046: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 19:09:26,046: INFO: common: created directory at: artifacts]
[2025-07-23 19:09:26,047: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 19:09:26,047: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 11, in <module>
    obj.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_injestion.py", line 13, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 27, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL'
[2025-07-23 19:12:55,840: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-23 19:12:55,843: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 19:12:55,845: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 19:12:55,846: INFO: common: created directory at: artifacts]
[2025-07-23 19:12:55,846: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 19:12:55,846: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 19:13:07,222: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-23 19:13:07,972: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-23 19:13:07,973: INFO: main: *******************]
[2025-07-23 19:13:07,973: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-23 19:13:07,976: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-23 19:13:07,978: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-23 19:13:07,978: INFO: common: created directory at: artifacts]
[2025-07-23 19:13:07,979: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-23 19:13:08,491: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-23 19:13:08,887: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 09:59:50,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 09:59:50,937: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 09:59:50,940: INFO: common: created directory at: artifacts]
[2025-07-24 09:59:50,942: INFO: common: created directory at: artifacts\training]
[2025-07-24 10:55:24,591: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-24 10:55:24,596: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 10:55:24,599: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 10:55:24,600: INFO: common: created directory at: artifacts]
[2025-07-24 10:55:24,600: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 10:55:24,601: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 10:55:35,979: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 10:55:36,728: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-24 10:55:36,728: INFO: main: *******************]
[2025-07-24 10:55:36,729: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 10:55:36,731: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 10:55:36,733: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 10:55:36,734: INFO: common: created directory at: artifacts]
[2025-07-24 10:55:36,734: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 10:55:37,306: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 10:55:37,617: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 10:55:37,618: INFO: main: *******************]
[2025-07-24 10:55:37,619: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 10:55:37,628: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 10:55:37,630: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 10:55:37,631: INFO: common: created directory at: artifacts]
[2025-07-24 10:55:37,632: INFO: common: created directory at: artifacts\training]
[2025-07-24 10:56:40,768: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 12:05:56,779: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 12:05:56,783: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 12:05:56,785: INFO: common: created directory at: artifacts]
[2025-07-24 12:06:14,506: INFO: common: json file saved at: scores.json]
[2025-07-24 12:06:19,410: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 12:06:20,357: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpst63u69z\model\data\model\assets]
[2025-07-24 12:10:04,628: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 12:10:04,632: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 12:10:04,633: INFO: common: created directory at: artifacts]
[2025-07-24 12:10:23,279: INFO: common: json file saved at: scores.json]
[2025-07-24 12:10:26,358: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 12:10:27,312: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpgxeq7x65\model\data\model\assets]
[2025-07-24 12:12:14,090: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 12:12:14,093: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 12:12:14,094: INFO: common: created directory at: artifacts]
[2025-07-24 12:12:32,357: INFO: common: json file saved at: scores.json]
[2025-07-24 12:12:35,357: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 12:12:36,302: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmprn7c7wc2\model\data\model\assets]
[2025-07-24 16:14:33,463: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 16:14:33,486: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 16:14:33,488: INFO: common: created directory at: artifacts]
[2025-07-24 16:14:54,834: INFO: common: json file saved at: scores.json]
[2025-07-24 16:14:58,254: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 16:14:59,385: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpqzjjeunh\model\data\model\assets]
[2025-07-24 17:04:39,196: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-24 17:04:39,199: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:04:39,201: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:04:39,201: INFO: common: created directory at: artifacts]
[2025-07-24 17:04:39,202: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 17:04:39,202: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 17:04:50,586: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 17:04:51,403: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-24 17:04:51,403: INFO: main: *******************]
[2025-07-24 17:04:51,403: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 17:04:51,406: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:04:51,408: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:04:51,409: INFO: common: created directory at: artifacts]
[2025-07-24 17:04:51,409: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 17:04:52,044: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 17:04:52,374: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 17:04:52,375: INFO: main: *******************]
[2025-07-24 17:04:52,376: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 17:04:52,380: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:04:52,383: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:04:52,383: INFO: common: created directory at: artifacts]
[2025-07-24 17:04:52,384: INFO: common: created directory at: artifacts\training]
[2025-07-24 17:05:47,391: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 17:05:47,391: INFO: main: *******************]
[2025-07-24 17:05:47,393: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 17:05:47,396: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:05:47,399: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:05:47,399: INFO: common: created directory at: artifacts]
[2025-07-24 17:06:05,085: INFO: common: json file saved at: scores.json]
[2025-07-24 17:06:05,086: INFO: common: json file saved at: scores.json]
[2025-07-24 17:06:05,086: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 17:13:50,868: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-24 17:13:50,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:13:50,882: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:13:50,883: INFO: common: created directory at: artifacts]
[2025-07-24 17:13:50,883: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 17:13:50,884: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 17:14:02,042: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 17:14:02,848: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-24 17:14:02,848: INFO: main: *******************]
[2025-07-24 17:14:02,849: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 17:14:02,852: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:14:02,856: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:14:02,856: INFO: common: created directory at: artifacts]
[2025-07-24 17:14:02,857: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 17:14:03,371: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 17:14:03,952: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 17:14:03,953: INFO: main: *******************]
[2025-07-24 17:14:03,955: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 17:14:03,958: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:14:03,962: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:14:03,963: INFO: common: created directory at: artifacts]
[2025-07-24 17:14:03,964: INFO: common: created directory at: artifacts\training]
[2025-07-24 17:16:45,047: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 17:16:45,048: INFO: main: *******************]
[2025-07-24 17:16:45,048: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 17:16:45,051: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:16:45,053: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:16:45,054: INFO: common: created directory at: artifacts]
[2025-07-24 17:17:02,654: INFO: common: json file saved at: scores.json]
[2025-07-24 17:17:02,654: INFO: common: json file saved at: scores.json]
[2025-07-24 17:17:02,654: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 17:30:57,379: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 17:30:57,383: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:30:57,386: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:30:57,386: INFO: common: created directory at: artifacts]
[2025-07-24 17:30:57,387: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 17:30:57,388: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 17:31:08,189: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 17:31:08,905: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 17:31:08,905: INFO: main: *******************]
[2025-07-24 17:31:08,906: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 17:31:08,909: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:31:08,911: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:31:08,912: INFO: common: created directory at: artifacts]
[2025-07-24 17:31:08,912: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 17:31:09,492: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 17:31:09,828: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 17:31:09,829: INFO: main: *******************]
[2025-07-24 17:31:09,829: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 17:31:09,833: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:31:09,835: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:31:09,836: INFO: common: created directory at: artifacts]
[2025-07-24 17:31:09,838: INFO: common: created directory at: artifacts\training]
[2025-07-24 17:32:04,835: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 17:32:04,836: INFO: main: *******************]
[2025-07-24 17:32:04,836: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 17:32:04,840: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:32:04,843: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:32:04,843: INFO: common: created directory at: artifacts]
[2025-07-24 17:32:22,342: INFO: common: json file saved at: scores.json]
[2025-07-24 17:32:22,342: INFO: common: json file saved at: scores.json]
[2025-07-24 17:32:22,343: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 17:33:48,343: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 17:33:48,345: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:33:48,347: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:33:48,347: INFO: common: created directory at: artifacts]
[2025-07-24 17:33:48,347: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 17:33:48,348: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 17:33:59,958: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 17:34:00,527: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 17:34:00,527: INFO: main: *******************]
[2025-07-24 17:34:00,528: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 17:34:00,533: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:34:00,540: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:34:00,542: INFO: common: created directory at: artifacts]
[2025-07-24 17:34:00,542: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 17:34:01,092: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 17:34:01,661: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 17:34:01,662: INFO: main: *******************]
[2025-07-24 17:34:01,664: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 17:34:01,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:34:01,675: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:34:01,675: INFO: common: created directory at: artifacts]
[2025-07-24 17:34:01,676: INFO: common: created directory at: artifacts\training]
[2025-07-24 17:34:57,336: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 17:34:57,337: INFO: main: *******************]
[2025-07-24 17:34:57,337: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 17:34:57,340: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:34:57,341: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:34:57,342: INFO: common: created directory at: artifacts]
[2025-07-24 17:35:14,533: INFO: common: json file saved at: scores.json]
[2025-07-24 17:35:14,533: INFO: common: json file saved at: scores.json]
[2025-07-24 17:35:14,534: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 17:42:58,939: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 17:42:58,941: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:42:58,943: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:42:58,944: INFO: common: created directory at: artifacts]
[2025-07-24 17:42:58,945: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 17:42:58,945: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 17:43:09,758: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 17:43:10,417: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 17:43:10,417: INFO: main: *******************]
[2025-07-24 17:43:10,418: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 17:43:10,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:43:10,422: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:43:10,423: INFO: common: created directory at: artifacts]
[2025-07-24 17:43:10,423: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 17:43:10,930: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 17:43:11,212: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 17:43:11,212: INFO: main: *******************]
[2025-07-24 17:43:11,213: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 17:43:11,215: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:43:11,217: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:43:11,218: INFO: common: created directory at: artifacts]
[2025-07-24 17:43:11,218: INFO: common: created directory at: artifacts\training]
[2025-07-24 17:44:05,922: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 17:44:05,922: INFO: main: *******************]
[2025-07-24 17:44:05,922: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 17:44:05,925: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 17:44:05,927: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 17:44:05,927: INFO: common: created directory at: artifacts]
[2025-07-24 17:44:23,408: INFO: common: json file saved at: scores.json]
[2025-07-24 17:44:23,409: INFO: common: json file saved at: scores.json]
[2025-07-24 17:44:23,409: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 18:03:21,337: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 18:03:21,340: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:03:21,342: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:03:21,342: INFO: common: created directory at: artifacts]
[2025-07-24 18:03:21,343: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 18:03:21,343: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:03:32,669: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:03:33,219: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 18:03:33,219: INFO: main: *******************]
[2025-07-24 18:03:33,219: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 18:03:33,222: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:03:33,224: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:03:33,224: INFO: common: created directory at: artifacts]
[2025-07-24 18:03:33,225: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 18:03:33,693: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 18:03:34,178: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 18:03:34,178: INFO: main: *******************]
[2025-07-24 18:03:34,179: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 18:03:34,188: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:03:34,189: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:03:34,191: INFO: common: created directory at: artifacts]
[2025-07-24 18:03:34,192: INFO: common: created directory at: artifacts\training]
[2025-07-24 18:04:28,262: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 18:04:28,263: INFO: main: *******************]
[2025-07-24 18:04:28,264: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 18:04:28,267: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:04:28,269: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:04:28,270: INFO: common: created directory at: artifacts]
[2025-07-24 18:04:45,384: INFO: common: json file saved at: scores.json]
[2025-07-24 18:04:45,385: INFO: common: json file saved at: scores.json]
[2025-07-24 18:04:48,416: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 18:04:49,287: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpx6nafqk0\model\data\model\assets]
[2025-07-24 18:05:25,621: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 18:16:54,957: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 18:16:54,960: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:16:54,963: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:16:54,963: INFO: common: created directory at: artifacts]
[2025-07-24 18:16:54,963: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 18:16:54,964: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:17:05,776: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:17:06,488: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 18:17:06,490: INFO: main: *******************]
[2025-07-24 18:17:06,496: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 18:17:06,512: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:17:06,519: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:17:06,520: INFO: common: created directory at: artifacts]
[2025-07-24 18:17:06,523: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 18:17:07,129: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 18:17:07,730: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 18:17:07,731: INFO: main: *******************]
[2025-07-24 18:17:07,733: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 18:17:07,737: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:17:07,742: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:17:07,743: INFO: common: created directory at: artifacts]
[2025-07-24 18:17:07,744: INFO: common: created directory at: artifacts\training]
[2025-07-24 18:19:52,159: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 18:19:52,160: INFO: main: *******************]
[2025-07-24 18:19:52,160: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 18:19:52,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:19:52,167: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:19:52,167: INFO: common: created directory at: artifacts]
[2025-07-24 18:20:09,166: INFO: common: json file saved at: scores.json]
[2025-07-24 18:20:09,167: INFO: common: json file saved at: scores.json]
[2025-07-24 18:20:12,201: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 18:20:13,083: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpsxcsvf9b\model\data\model\assets]
[2025-07-24 18:20:49,920: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 18:25:10,940: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 18:25:10,943: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:25:10,953: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:25:10,954: INFO: common: created directory at: artifacts]
[2025-07-24 18:25:10,954: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 18:25:10,955: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:25:22,945: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:25:23,599: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 18:25:23,600: INFO: main: *******************]
[2025-07-24 18:25:23,600: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 18:25:23,603: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:25:23,606: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:25:23,606: INFO: common: created directory at: artifacts]
[2025-07-24 18:25:23,607: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 18:25:24,196: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 18:25:24,775: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 18:25:24,776: INFO: main: *******************]
[2025-07-24 18:25:24,777: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 18:25:24,779: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:25:24,781: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:25:24,782: INFO: common: created directory at: artifacts]
[2025-07-24 18:25:24,782: INFO: common: created directory at: artifacts\training]
[2025-07-24 18:27:14,815: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 18:27:14,815: INFO: main: *******************]
[2025-07-24 18:27:14,816: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 18:27:14,818: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:27:14,820: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:27:14,821: INFO: common: created directory at: artifacts]
[2025-07-24 18:27:31,929: INFO: common: json file saved at: scores.json]
[2025-07-24 18:27:31,930: INFO: common: json file saved at: scores.json]
[2025-07-24 18:27:34,956: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 18:27:35,906: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmp37zf_b2z\model\data\model\assets]
[2025-07-24 18:28:13,063: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 18:33:31,004: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 18:33:31,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:33:31,016: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:33:31,017: INFO: common: created directory at: artifacts]
[2025-07-24 18:33:31,017: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 18:33:31,019: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:33:44,826: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:33:45,533: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 18:33:45,533: INFO: main: *******************]
[2025-07-24 18:33:45,533: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 18:33:45,536: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:33:45,538: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:33:45,538: INFO: common: created directory at: artifacts]
[2025-07-24 18:33:45,539: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 18:33:46,087: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 18:33:46,327: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 18:33:46,328: INFO: main: *******************]
[2025-07-24 18:33:46,329: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 18:33:46,340: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:33:46,343: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:33:46,343: INFO: common: created directory at: artifacts]
[2025-07-24 18:33:46,344: INFO: common: created directory at: artifacts\training]
[2025-07-24 18:34:40,181: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 18:34:40,182: INFO: main: *******************]
[2025-07-24 18:34:40,183: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 18:34:40,186: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:34:40,188: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:34:40,188: INFO: common: created directory at: artifacts]
[2025-07-24 18:34:57,489: INFO: common: json file saved at: scores.json]
[2025-07-24 18:34:57,490: INFO: common: json file saved at: scores.json]
[2025-07-24 18:34:59,235: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 18:35:00,169: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpyp4w4rv3\model\data\model\assets]
[2025-07-24 18:35:12,693: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 56, in <module>
    model_evalution.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 19, in main
    evaluation.log_into_mlflow()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 67, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 150, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 192, in _copy_one
    file_util.copy_file(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-07-24 18:37:21,510: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 18:37:21,513: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:37:21,515: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:37:21,516: INFO: common: created directory at: artifacts]
[2025-07-24 18:37:21,516: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 18:37:21,517: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:37:32,299: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:37:33,101: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 18:37:33,102: INFO: main: *******************]
[2025-07-24 18:37:33,102: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 18:37:33,105: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:37:33,107: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:37:33,107: INFO: common: created directory at: artifacts]
[2025-07-24 18:37:33,108: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 18:37:33,588: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 18:37:33,871: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 18:37:33,872: INFO: main: *******************]
[2025-07-24 18:37:33,877: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 18:37:33,880: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:37:33,882: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:37:33,883: INFO: common: created directory at: artifacts]
[2025-07-24 18:37:33,884: INFO: common: created directory at: artifacts\training]
[2025-07-24 18:38:27,860: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 18:38:27,861: INFO: main: *******************]
[2025-07-24 18:38:27,863: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 18:38:27,869: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:38:27,871: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:38:27,871: INFO: common: created directory at: artifacts]
[2025-07-24 18:38:45,765: INFO: common: json file saved at: scores.json]
[2025-07-24 18:38:45,766: INFO: common: json file saved at: scores.json]
[2025-07-24 18:38:46,735: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 56, in <module>
    model_evalution.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 19, in main
    evaluation.log_into_mlflow()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 58, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-07-24 18:40:26,567: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 18:40:26,570: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:40:26,571: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:40:26,572: INFO: common: created directory at: artifacts]
[2025-07-24 18:40:26,572: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 18:40:26,572: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:40:37,338: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:40:37,888: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 18:40:37,888: INFO: main: *******************]
[2025-07-24 18:40:37,888: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 18:40:37,891: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:40:37,893: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:40:37,894: INFO: common: created directory at: artifacts]
[2025-07-24 18:40:37,895: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 18:40:38,386: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 18:40:39,026: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 18:40:39,026: INFO: main: *******************]
[2025-07-24 18:40:39,028: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 18:40:39,031: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:40:39,038: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:40:39,039: INFO: common: created directory at: artifacts]
[2025-07-24 18:40:39,039: INFO: common: created directory at: artifacts\training]
[2025-07-24 18:41:33,657: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 18:41:33,658: INFO: main: *******************]
[2025-07-24 18:41:33,658: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 18:41:33,662: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:41:33,665: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:41:33,665: INFO: common: created directory at: artifacts]
[2025-07-24 18:41:51,004: INFO: common: json file saved at: scores.json]
[2025-07-24 18:41:51,005: INFO: common: json file saved at: scores.json]
[2025-07-24 18:41:52,828: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 18:41:53,732: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpbv8umnrf\model\data\model\assets]
[2025-07-24 18:42:05,421: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 56, in <module>
    model_evalution.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 19, in main
    evaluation.log_into_mlflow()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 67, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 150, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 192, in _copy_one
    file_util.copy_file(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-07-24 18:45:10,096: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 18:45:10,099: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:45:10,100: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:45:10,101: INFO: common: created directory at: artifacts]
[2025-07-24 18:45:10,102: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 18:45:10,102: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:45:21,211: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:45:21,855: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 18:45:21,855: INFO: main: *******************]
[2025-07-24 18:45:21,856: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 18:45:21,858: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:45:21,860: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:45:21,860: INFO: common: created directory at: artifacts]
[2025-07-24 18:45:21,861: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 18:45:22,402: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 18:45:22,629: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 18:45:22,629: INFO: main: *******************]
[2025-07-24 18:45:22,630: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 18:45:22,633: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:45:22,634: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:45:22,635: INFO: common: created directory at: artifacts]
[2025-07-24 18:45:22,636: INFO: common: created directory at: artifacts\training]
[2025-07-24 18:46:15,867: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 18:46:15,868: INFO: main: *******************]
[2025-07-24 18:46:15,868: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 18:46:15,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:46:15,873: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:46:15,874: INFO: common: created directory at: artifacts]
[2025-07-24 18:46:32,958: INFO: common: json file saved at: scores.json]
[2025-07-24 18:46:32,959: INFO: common: json file saved at: scores.json]
[2025-07-24 18:46:35,987: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 18:46:36,927: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpe8pb05ka\model\data\model\assets]
[2025-07-24 18:47:14,029: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 18:49:58,874: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 18:49:58,877: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:49:58,880: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:49:58,881: INFO: common: created directory at: artifacts]
[2025-07-24 18:49:58,881: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 18:49:58,882: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:50:09,730: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 18:50:10,521: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 18:50:10,521: INFO: main: *******************]
[2025-07-24 18:50:10,522: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 18:50:10,525: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:50:10,527: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:50:10,528: INFO: common: created directory at: artifacts]
[2025-07-24 18:50:10,528: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 18:50:11,092: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 18:50:11,640: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 18:50:11,640: INFO: main: *******************]
[2025-07-24 18:50:11,642: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 18:50:11,645: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:50:11,648: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:50:11,649: INFO: common: created directory at: artifacts]
[2025-07-24 18:50:11,650: INFO: common: created directory at: artifacts\training]
[2025-07-24 18:51:58,547: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 18:51:58,547: INFO: main: *******************]
[2025-07-24 18:51:58,548: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 18:51:58,551: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 18:51:58,553: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 18:51:58,553: INFO: common: created directory at: artifacts]
[2025-07-24 18:52:15,429: INFO: common: json file saved at: scores.json]
[2025-07-24 18:52:15,430: INFO: common: json file saved at: scores.json]
[2025-07-24 18:52:18,432: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 18:52:19,361: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpp46jsdj2\model\data\model\assets]
[2025-07-24 18:52:56,438: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 19:00:19,502: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 19:00:19,505: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:00:19,507: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:00:19,507: INFO: common: created directory at: artifacts]
[2025-07-24 19:00:19,508: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 19:00:19,508: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 19:00:31,721: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 19:00:32,482: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 19:00:32,482: INFO: main: *******************]
[2025-07-24 19:00:32,483: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 19:00:32,485: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:00:32,487: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:00:32,488: INFO: common: created directory at: artifacts]
[2025-07-24 19:00:32,488: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 19:00:32,960: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 19:00:33,250: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 19:00:33,250: INFO: main: *******************]
[2025-07-24 19:00:33,252: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 19:00:33,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:00:33,259: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:00:33,259: INFO: common: created directory at: artifacts]
[2025-07-24 19:00:33,260: INFO: common: created directory at: artifacts\training]
[2025-07-24 19:02:21,291: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 19:02:21,291: INFO: main: *******************]
[2025-07-24 19:02:21,292: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 19:02:21,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:02:21,297: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:02:21,297: INFO: common: created directory at: artifacts]
[2025-07-24 19:02:38,616: INFO: common: json file saved at: scores.json]
[2025-07-24 19:02:38,616: INFO: common: json file saved at: scores.json]
[2025-07-24 19:02:41,679: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 19:02:42,543: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpjbxic58x\model\data\model\assets]
[2025-07-24 19:03:19,722: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 19:12:46,283: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:12:46,287: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:12:46,289: INFO: common: created directory at: artifacts]
[2025-07-24 19:13:08,085: INFO: common: json file saved at: scores.json]
[2025-07-24 19:13:11,389: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-24 19:13:12,572: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpih5seker\model\data\model\assets]
[2025-07-24 19:31:34,857: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 19:31:34,863: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:31:34,866: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:31:34,866: INFO: common: created directory at: artifacts]
[2025-07-24 19:31:34,867: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 19:31:34,867: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 19:31:45,746: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 19:31:46,557: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 19:31:46,558: INFO: main: *******************]
[2025-07-24 19:31:46,560: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 19:31:46,566: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:31:46,568: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:31:46,568: INFO: common: created directory at: artifacts]
[2025-07-24 19:31:46,568: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 19:31:47,216: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 19:31:47,630: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 19:31:47,630: INFO: main: *******************]
[2025-07-24 19:31:47,632: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 19:31:47,642: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:31:47,645: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:31:47,646: INFO: common: created directory at: artifacts]
[2025-07-24 19:31:47,648: INFO: common: created directory at: artifacts\training]
[2025-07-24 19:32:50,702: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 19:32:50,702: INFO: main: *******************]
[2025-07-24 19:32:50,704: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 19:32:50,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:32:50,710: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:32:50,711: INFO: common: created directory at: artifacts]
[2025-07-24 19:33:09,885: INFO: common: json file saved at: scores.json]
[2025-07-24 19:33:09,885: INFO: common: json file saved at: scores.json]
[2025-07-24 19:33:09,885: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-24 19:33:47,254: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-24 19:33:47,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:33:47,259: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:33:47,260: INFO: common: created directory at: artifacts]
[2025-07-24 19:33:47,260: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-24 19:33:47,261: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 19:33:57,956: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-24 19:33:58,602: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-24 19:33:58,603: INFO: main: *******************]
[2025-07-24 19:33:58,604: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-24 19:33:58,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:33:58,622: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:33:58,623: INFO: common: created directory at: artifacts]
[2025-07-24 19:33:58,625: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-24 19:33:59,139: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-24 19:33:59,939: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-24 19:33:59,939: INFO: main: *******************]
[2025-07-24 19:33:59,942: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-24 19:33:59,945: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:33:59,948: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:33:59,949: INFO: common: created directory at: artifacts]
[2025-07-24 19:33:59,949: INFO: common: created directory at: artifacts\training]
[2025-07-24 19:35:51,240: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-24 19:35:51,240: INFO: main: *******************]
[2025-07-24 19:35:51,241: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-24 19:35:51,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-24 19:35:51,245: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-24 19:35:51,246: INFO: common: created directory at: artifacts]
[2025-07-24 19:36:08,147: INFO: common: json file saved at: scores.json]
[2025-07-24 19:36:08,147: INFO: common: json file saved at: scores.json]
[2025-07-24 19:36:08,147: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-25 12:21:17,477: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 12:21:17,498: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:21:17,517: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:21:17,518: INFO: common: created directory at: artifacts]
[2025-07-25 12:21:17,519: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 12:21:17,520: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:21:29,178: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:21:30,494: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 12:21:30,495: INFO: main: *******************]
[2025-07-25 12:21:30,496: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 12:21:30,502: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:21:30,508: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:21:30,510: INFO: common: created directory at: artifacts]
[2025-07-25 12:21:30,512: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 12:21:31,955: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 12:21:32,389: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 12:21:32,391: INFO: main: *******************]
[2025-07-25 12:21:32,394: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 12:21:32,404: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:21:32,412: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:21:32,414: INFO: common: created directory at: artifacts]
[2025-07-25 12:21:32,415: INFO: common: created directory at: artifacts\training]
[2025-07-25 12:22:37,726: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-25 12:22:37,727: INFO: main: *******************]
[2025-07-25 12:22:37,727: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-25 12:22:37,730: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:22:37,732: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:22:37,733: INFO: common: created directory at: artifacts]
[2025-07-25 12:22:54,904: INFO: common: json file saved at: scores.json]
[2025-07-25 12:22:54,906: INFO: common: json file saved at: scores.json]
[2025-07-25 12:22:54,906: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-25 12:27:01,459: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 12:27:01,463: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:27:01,467: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:27:01,468: INFO: common: created directory at: artifacts]
[2025-07-25 12:27:01,468: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 12:27:01,469: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:27:17,394: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:27:17,956: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 12:27:17,956: INFO: main: *******************]
[2025-07-25 12:27:17,957: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 12:27:17,962: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:27:17,964: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:27:17,965: INFO: common: created directory at: artifacts]
[2025-07-25 12:27:17,965: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 12:27:18,441: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 12:27:19,129: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 12:27:19,130: INFO: main: *******************]
[2025-07-25 12:27:19,132: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 12:27:19,137: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:27:19,141: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:27:19,142: INFO: common: created directory at: artifacts]
[2025-07-25 12:27:19,143: INFO: common: created directory at: artifacts\training]
[2025-07-25 12:29:08,298: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-25 12:29:08,299: INFO: main: *******************]
[2025-07-25 12:29:08,299: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-25 12:29:08,304: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:29:08,307: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:29:08,308: INFO: common: created directory at: artifacts]
[2025-07-25 12:29:25,633: INFO: common: json file saved at: scores.json]
[2025-07-25 12:29:25,634: INFO: common: json file saved at: scores.json]
[2025-07-25 12:29:28,990: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-25 12:29:29,981: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpivta24yb\model\data\model\assets]
[2025-07-25 12:30:12,503: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 56, in <module>
    model_evalution.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 72, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 562, in log
    mlflow.register_model(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 77, in register_model
    raise e
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 68, in register_model
    create_model_response = client.create_registered_model(name)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1743, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\store\model_registry\rest_store.py", line 75, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 42, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: ''
[2025-07-25 12:50:07,385: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 12:50:07,387: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:50:07,403: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:50:07,403: INFO: common: created directory at: artifacts]
[2025-07-25 12:50:07,404: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 12:50:07,405: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:50:18,488: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:50:19,037: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 12:50:19,038: INFO: main: *******************]
[2025-07-25 12:50:19,038: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 12:50:19,041: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:50:19,043: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:50:19,044: INFO: common: created directory at: artifacts]
[2025-07-25 12:50:19,044: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 12:50:19,527: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 12:50:20,161: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 12:50:20,162: INFO: main: *******************]
[2025-07-25 12:50:20,165: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 12:50:20,170: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:50:20,175: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:50:20,176: INFO: common: created directory at: artifacts]
[2025-07-25 12:50:20,177: INFO: common: created directory at: artifacts\training]
[2025-07-25 12:50:25,365: ERROR: main: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
    model_trainer.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
    self.model.fit(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]
[2025-07-25 12:51:29,048: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 12:51:29,051: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:51:29,053: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:51:29,053: INFO: common: created directory at: artifacts]
[2025-07-25 12:51:29,053: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 12:51:29,054: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:51:39,831: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:51:40,381: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 12:51:40,381: INFO: main: *******************]
[2025-07-25 12:51:40,382: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 12:51:40,385: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:51:40,387: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:51:40,387: INFO: common: created directory at: artifacts]
[2025-07-25 12:51:40,388: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 12:51:40,876: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 12:51:41,540: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 12:51:41,541: INFO: main: *******************]
[2025-07-25 12:51:41,543: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 12:51:41,551: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:51:41,554: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:51:41,555: INFO: common: created directory at: artifacts]
[2025-07-25 12:51:41,556: INFO: common: created directory at: artifacts\training]
[2025-07-25 12:51:46,355: ERROR: main: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
    model_trainer.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
    self.model.fit(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]
[2025-07-25 12:53:37,047: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 12:53:37,050: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:53:37,053: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:53:37,054: INFO: common: created directory at: artifacts]
[2025-07-25 12:53:37,054: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 12:53:37,054: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:53:51,651: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:53:52,191: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 12:53:52,191: INFO: main: *******************]
[2025-07-25 12:53:52,192: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 12:53:52,195: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:53:52,197: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:53:52,198: INFO: common: created directory at: artifacts]
[2025-07-25 12:53:52,199: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 12:53:52,686: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 12:53:53,593: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 12:53:53,594: INFO: main: *******************]
[2025-07-25 12:53:53,599: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 12:53:53,612: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:53:53,621: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:53:53,623: INFO: common: created directory at: artifacts]
[2025-07-25 12:53:53,626: INFO: common: created directory at: artifacts\training]
[2025-07-25 12:53:58,864: ERROR: main: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
    model_trainer.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
    self.model.fit(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]
[2025-07-25 12:55:21,462: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 12:55:21,465: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:55:21,467: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:55:21,467: INFO: common: created directory at: artifacts]
[2025-07-25 12:55:21,468: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 12:55:21,469: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:55:32,491: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:55:33,266: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 12:55:33,267: INFO: main: *******************]
[2025-07-25 12:55:33,267: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 12:55:33,270: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:55:33,273: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:55:33,273: INFO: common: created directory at: artifacts]
[2025-07-25 12:55:33,274: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 12:55:33,762: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 12:55:33,984: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 12:55:33,985: INFO: main: *******************]
[2025-07-25 12:55:33,986: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 12:55:33,997: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:55:34,001: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:55:34,002: INFO: common: created directory at: artifacts]
[2025-07-25 12:55:34,004: INFO: common: created directory at: artifacts\training]
[2025-07-25 12:55:39,191: ERROR: main: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
    model_trainer.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
    self.model.fit(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]
[2025-07-25 12:57:18,322: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 12:57:18,326: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:57:18,327: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:57:18,329: INFO: common: created directory at: artifacts]
[2025-07-25 12:57:18,329: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 12:57:18,329: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:57:29,495: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:57:30,109: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 12:57:30,110: INFO: main: *******************]
[2025-07-25 12:57:30,110: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 12:57:30,113: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:57:30,115: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:57:30,116: INFO: common: created directory at: artifacts]
[2025-07-25 12:57:30,117: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 12:57:30,656: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 12:57:31,221: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 12:57:31,222: INFO: main: *******************]
[2025-07-25 12:57:31,223: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 12:57:31,228: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:57:31,232: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:57:31,232: INFO: common: created directory at: artifacts]
[2025-07-25 12:57:31,233: INFO: common: created directory at: artifacts\training]
[2025-07-25 12:57:36,520: ERROR: main: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
    model_trainer.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
    self.model.fit(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]
[2025-07-25 12:58:37,413: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 12:58:37,416: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:58:37,432: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:58:37,433: INFO: common: created directory at: artifacts]
[2025-07-25 12:58:37,434: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 12:58:37,436: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:58:48,426: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 12:58:49,073: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 12:58:49,074: INFO: main: *******************]
[2025-07-25 12:58:49,074: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 12:58:49,077: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:58:49,079: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:58:49,080: INFO: common: created directory at: artifacts]
[2025-07-25 12:58:49,081: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 12:58:49,626: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 12:58:50,019: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 12:58:50,020: INFO: main: *******************]
[2025-07-25 12:58:50,020: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 12:58:50,023: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 12:58:50,025: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 12:58:50,027: INFO: common: created directory at: artifacts]
[2025-07-25 12:58:50,027: INFO: common: created directory at: artifacts\training]
[2025-07-25 12:58:56,485: ERROR: main: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
    model_trainer.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.train()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
    self.model.fit(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 42, in <module>
      model_trainer.main()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
      training.train()
    File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
      self.model.fit(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]
[2025-07-25 16:22:41,253: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 16:22:41,258: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:22:41,272: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:22:41,273: INFO: common: created directory at: artifacts]
[2025-07-25 16:22:41,273: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 16:22:41,274: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 16:22:52,964: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 16:22:53,633: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 16:22:53,633: INFO: main: *******************]
[2025-07-25 16:22:53,633: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 16:22:53,638: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:22:53,641: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:22:53,642: INFO: common: created directory at: artifacts]
[2025-07-25 16:22:53,643: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 16:22:54,935: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 16:22:55,591: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 16:22:55,593: INFO: main: *******************]
[2025-07-25 16:22:55,594: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 16:22:55,599: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:22:55,604: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:22:55,606: INFO: common: created directory at: artifacts]
[2025-07-25 16:22:55,607: INFO: common: created directory at: artifacts\training]
[2025-07-25 16:24:12,476: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-25 16:24:12,476: INFO: main: *******************]
[2025-07-25 16:24:12,476: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-25 16:24:12,480: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:24:12,483: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:24:12,484: INFO: common: created directory at: artifacts]
[2025-07-25 16:24:29,785: INFO: common: json file saved at: scores.json]
[2025-07-25 16:24:29,786: INFO: common: json file saved at: scores.json]
[2025-07-25 16:24:32,994: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-25 16:24:33,922: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpznltdln7\model\data\model\assets]
[2025-07-25 16:25:14,298: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\code\Ai-engineer-project-microsoft\New folder\Project\All Project\6-a-Kidney-Disease-Classification-Deep-Learning-Project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 56, in <module>
    model_evalution.main()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\code\ai-engineer-project-microsoft\new folder\project\all project\6-a-kidney-disease-classification-deep-learning-project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 72, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 562, in log
    mlflow.register_model(
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 77, in register_model
    raise e
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 68, in register_model
    create_model_response = client.create_registered_model(name)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1743, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\store\model_registry\rest_store.py", line 75, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 42, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\DELL\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: ''
[2025-07-25 16:28:38,483: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 16:28:38,486: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:28:38,488: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:28:38,489: INFO: common: created directory at: artifacts]
[2025-07-25 16:28:38,489: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 16:28:38,489: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 16:28:49,585: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 16:28:50,166: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 16:28:50,167: INFO: main: *******************]
[2025-07-25 16:28:50,167: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 16:28:50,170: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:28:50,171: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:28:50,172: INFO: common: created directory at: artifacts]
[2025-07-25 16:28:50,173: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 16:28:50,704: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 16:28:51,398: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 16:28:51,400: INFO: main: *******************]
[2025-07-25 16:28:51,400: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 16:28:51,409: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:28:51,417: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:28:51,419: INFO: common: created directory at: artifacts]
[2025-07-25 16:28:51,421: INFO: common: created directory at: artifacts\training]
[2025-07-25 16:29:48,798: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-25 16:29:48,799: INFO: main: *******************]
[2025-07-25 16:29:48,800: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-25 16:29:48,808: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:29:48,816: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:29:48,818: INFO: common: created directory at: artifacts]
[2025-07-25 16:30:06,090: INFO: common: json file saved at: scores.json]
[2025-07-25 16:30:06,091: INFO: common: json file saved at: scores.json]
[2025-07-25 16:30:09,230: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-25 16:30:10,082: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpy6lhac8u\model\data\model\assets]
[2025-07-25 16:30:50,082: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-25 16:30:50,881: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpgvc7qbtm\model\data\model\assets]
[2025-07-25 16:31:26,772: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-25 16:33:53,305: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-25 16:33:53,312: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:33:53,333: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:33:53,334: INFO: common: created directory at: artifacts]
[2025-07-25 16:33:53,335: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 16:33:53,336: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 16:34:04,942: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 16:34:06,176: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-25 16:34:06,176: INFO: main: *******************]
[2025-07-25 16:34:06,177: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-25 16:34:06,183: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:34:06,186: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:34:06,187: INFO: common: created directory at: artifacts]
[2025-07-25 16:34:06,188: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-25 16:34:07,295: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 16:34:08,110: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 16:34:08,111: INFO: main: *******************]
[2025-07-25 16:34:08,112: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-25 16:34:08,117: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:34:08,122: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:34:08,124: INFO: common: created directory at: artifacts]
[2025-07-25 16:34:08,126: INFO: common: created directory at: artifacts\training]
[2025-07-25 16:36:05,847: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-25 16:36:05,848: INFO: main: *******************]
[2025-07-25 16:36:05,848: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-25 16:36:05,854: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 16:36:05,861: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 16:36:05,863: INFO: common: created directory at: artifacts]
[2025-07-25 16:36:22,965: INFO: common: json file saved at: scores.json]
[2025-07-25 16:36:22,966: INFO: common: json file saved at: scores.json]
[2025-07-25 16:36:25,994: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-25 16:36:26,893: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpvcvt0mn3\model\data\model\assets]
[2025-07-25 16:37:07,219: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-25 16:37:08,078: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmp4qdc4iqk\model\data\model\assets]
[2025-07-25 16:37:44,225: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-25 19:32:30,297: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-25 19:32:30,300: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 19:32:30,304: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 19:32:30,305: INFO: common: created directory at: artifacts]
[2025-07-25 19:32:30,306: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 19:32:30,307: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 19:32:41,461: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 19:32:42,354: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-25 19:39:44,066: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-25 19:39:44,069: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 19:39:44,070: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 19:39:44,071: INFO: common: created directory at: artifacts]
[2025-07-25 19:39:44,071: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 19:39:44,072: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 19:39:55,774: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 19:39:56,517: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-25 19:40:04,096: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-25 19:40:04,099: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 19:40:04,101: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 19:40:04,102: INFO: common: created directory at: artifacts]
[2025-07-25 19:40:04,103: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 19:40:04,104: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 19:40:15,006: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 19:40:15,652: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-25 19:40:33,605: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-25 19:40:33,608: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 19:40:33,610: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 19:40:33,611: INFO: common: created directory at: artifacts]
[2025-07-25 19:40:33,611: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 19:40:33,611: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 19:40:44,293: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-25 19:40:44,871: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 12:57:17,559: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 12:57:17,635: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 12:57:17,650: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 12:57:17,651: INFO: common: created directory at: artifacts]
[2025-07-26 12:57:17,653: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 12:57:17,654: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 12:57:30,664: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 12:57:31,338: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 13:00:50,825: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 13:00:50,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:00:50,831: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:00:50,832: INFO: common: created directory at: artifacts]
[2025-07-26 13:00:50,833: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 13:00:50,833: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:01:05,666: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:01:06,310: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 13:22:30,951: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 13:22:30,954: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:22:30,956: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:22:30,957: INFO: common: created directory at: artifacts]
[2025-07-26 13:22:30,957: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 13:22:30,958: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:22:41,952: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:22:42,951: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 13:28:21,018: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 13:28:21,021: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:28:21,024: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:28:21,025: INFO: common: created directory at: artifacts]
[2025-07-26 13:28:21,025: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 13:28:21,026: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:28:31,953: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:28:32,758: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 13:30:32,824: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 13:30:32,828: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:30:32,830: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:30:32,831: INFO: common: created directory at: artifacts]
[2025-07-26 13:30:32,831: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 13:30:32,832: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:30:43,825: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:30:44,944: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 13:33:33,371: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:33:33,375: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:33:33,377: INFO: common: created directory at: artifacts]
[2025-07-26 13:33:33,379: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 13:33:33,383: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:33:44,747: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:34:03,837: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:34:03,842: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:34:03,844: INFO: common: created directory at: artifacts]
[2025-07-26 13:34:03,846: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-26 13:34:04,607: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-26 13:34:22,664: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:34:22,670: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:34:22,673: INFO: common: created directory at: artifacts]
[2025-07-26 13:34:22,675: INFO: common: created directory at: artifacts\training]
[2025-07-26 13:35:54,152: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:35:54,157: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:35:54,159: INFO: common: created directory at: artifacts]
[2025-07-26 13:36:13,376: INFO: common: json file saved at: scores.json]
[2025-07-26 13:36:17,132: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-26 13:36:18,188: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpheuk_iaf\model\data\model\assets]
[2025-07-26 13:38:02,300: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 13:38:02,303: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:38:02,305: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:38:02,306: INFO: common: created directory at: artifacts]
[2025-07-26 13:38:02,306: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 13:38:02,307: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:38:13,232: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:38:13,978: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 13:47:56,920: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 13:47:56,924: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:47:56,926: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:47:56,927: INFO: common: created directory at: artifacts]
[2025-07-26 13:47:56,928: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 13:47:56,928: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:48:07,694: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:48:08,381: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 13:52:28,468: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 13:52:28,471: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:52:28,473: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:52:28,474: INFO: common: created directory at: artifacts]
[2025-07-26 13:52:28,475: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 13:52:28,475: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:52:46,124: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:52:46,785: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 13:54:01,534: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 13:54:01,537: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 13:54:01,539: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 13:54:01,540: INFO: common: created directory at: artifacts]
[2025-07-26 13:54:01,540: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 13:54:01,541: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:54:12,346: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 13:54:12,996: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 14:02:28,395: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 14:02:28,400: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 14:02:28,403: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 14:02:28,404: INFO: common: created directory at: artifacts]
[2025-07-26 14:02:28,405: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 14:02:28,405: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 14:02:43,987: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 14:02:45,490: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 14:03:12,915: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 14:03:12,919: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 14:03:12,923: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 14:03:12,924: INFO: common: created directory at: artifacts]
[2025-07-26 14:03:12,925: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 14:03:12,926: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 14:04:21,923: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 14:04:23,334: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 14:07:10,041: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-07-26 14:07:10,044: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-26 14:07:10,047: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-26 14:07:10,047: INFO: common: created directory at: artifacts]
[2025-07-26 14:07:10,048: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 14:07:10,049: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 14:07:25,346: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-26 14:07:25,996: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
